services:
  php:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - db  # PHP будет ждать запуска базы данных

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: SpyPerson
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      # ДОБАВЬТЕ ЭТУ СТРОКУ:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-panel
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db        # Указываем на имя сервиса базы данных
      PMA_PORT: 3306
    ports:
      - "8081:80"
    networks:
      - app-network       # ОБЯЗАТЕЛЬНО та же сеть, что у базы

networks:
  app-network:
    driver: bridge

# Обязательно добавь это в конец файла, чтобы данные базы сохранялись на диске
volumes:
  db_data: